server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
